### ISSUE TITLE
Javadoc generated in English has German language indicated in HTML tag

### ISSUE THREAD

**Issue by mminella** [spring-projects/spring-data-build#1048]
The generated javadoc for Spring Data Mongodb (although I have not checked the other Spring Data projects), is generating the HTML tag with the `de` language.  This causes Chrome to think it's in German and ask users if they want it translated.  This `lang` attribute should either be changed to the actual language or removed entirely.

**Comment by odrotbohm** [comment]
Setting the Javadoc `locale` flag to `en_US` should do the trick here. Great catch!

**Comment by kriegaex** [comment]
I just noticed in another project that this seems to be broken again in JDK 20+ after having been fixed for JDK 15. Can you verify and confirm? For me, this switch has no effect on JDK 21. See https://bugs.openjdk.org/browse/JDK-8222793.

**Comment by kriegaex** [comment]
I am too busy for contributing a PR just now, but found this workaround for my project that does not require setting `JAVA_TOOL_OPTIONS`:

```xml
<!--
  Avoid non-English javadoc generation. Due to https://bugs.openjdk.org/browse/JDK-8222793 reoccurring at
  least in JDKs 19-21 and also being broken in some older JDKs, we cannot rely on just setting the locale
  parameter, but also need the 'user.language' and 'user.country' parameters in 'additionalJOptions' as a
  workaround.
-->
<locale>en</locale>
<additionalJOptions>
  <additionalJOption>-J-Dfile.encoding=UTF-8</additionalJOption>
  <additionalJOption>-J-Duser.language=en</additionalJOption>
  <additionalJOption>-J-Duser.country=US</additionalJOption>
</additionalJOptions>
```

See also https://github.com/eclipse-aspectj/aspectj/commit/0cba9d10b7a4987af5654e3e1fa84c7f76745e23.
