### ISSUE TITLE
Kotlin version inconsistency?

### ISSUE THREAD

**Issue by sothawo** [spring-projects/spring-data-build#1452]
in parent/pom the Kotlin version is defined as 1.5.0 (https://github.com/spring-projects/spring-data-build/blob/main/parent/pom.xml#L115).

But the kotlin-maven-plugin is configured to be on API and language level 1.3 (https://github.com/spring-projects/spring-data-build/blob/main/parent/pom.xml#L1122-L1130)

Is this on purpose? This prevents using functions like _Collection.reduceOrNull()_  which were introduced in 1.4

**Comment by mp911de** [comment]
This setup is on purpose. We want to make use of the latest library versions while ensuring the 1.3 API compatibility level, similar to [Spring Framework](https://github.com/spring-projects/spring-framework/blob/f854803e1822d8751380f10b324b97031ec943f9/build.gradle#L313-L328).
