### ISSUE TITLE
Upgrade to Checkstyle 8.45.1

### ISSUE THREAD

**Issue by schauder** [spring-projects/spring-data-build#1501]

**Comment by michael-simons** [comment]
This broke our build: https://github.com/spring-projects/spring-data-neo4j/commit/6f109576cd1aa0933d995ced7c5e36c8eee3b35e

https://jenkins.spring.io/blue/organizations/jenkins/spring-data-neo4j/detail/main/135/

**Comment by schauder** [comment]
@michael-simons I'm sorry. But you fixed it on your side, correct?

**Comment by michael-simons** [comment]
Yep, thanks and no worries. Just wanted to let you know, maybe this occurred in other projects too.
