### ISSUE TITLE
Docs Search by Algolia returns 403

### ISSUE THREAD

**Issue by ilkou** [spring-projects/spring-data-build#2310]
Hello!

I'm trying to search in the [spring-data docs](https://docs.spring.io/spring-data), but the UI doesn't display any results. When I inspected the Network tab, I noticed that `Algolia` endpoint is returning `403 Forbidden` with the following response:

```json
{"message":"Invalid Application-ID or API key","status":403}
```

**Steps to Reproduce**:
1. Go to [spring-data docs](https://docs.spring.io/spring-data).
2. Attempt to use the search functionality.
3. Observe the lack of results and check the browser's Network tab for errors.

I apologize if this is not the right place to report such an incident, and thanks for the great project!

**Comment by mp911de** [comment]
The search has been broken because of changed credentials. We've upgraded our build to pick up the correct ones via https://github.com/spring-projects/spring-data-dev-tools/issues/226.
