### ISSUE TITLE
Introduce groovy script to automatically create issue branches and update project versions.

### ISSUE THREAD

**Issue by thomasdarimont** [spring-projects/spring-data-build#32]
We should use groovy for such sophisticated automation steps since it allows faster development and easier debugging than shell scripts.

Currently every branch push / commit ends up in the same BUILD-SNAPSHOT artifact. In order to avoid potential confusion we should change the pom versions to create issue specific snapshot-builds next to the build-snapshot that is created for the master branch by a script.

Requirements:
- Executable via console
- Debuggable via IDE
- Works with maven AND gradle projects.

This deprecates the new-issue-branch.sh shell script introduced in #27

**Comment by mp911de** [comment]
We do not plan on working on that issue.
