### ISSUE TITLE
Move either sources generated by delombok or move the build step to a different profile

### ISSUE THREAD

**Issue by schauder** [spring-projects/spring-data-build#481]
The recent addition of delombok to the build causes issue in IntelliJ. It detects the sources and complains about seeing the sources twice.

In order to avoid this we could either generate them into a separate direactory, not under `generated-sources` so IntelliJ won't detect them.

Or we could move the delombok action into a profile (CI?) that normally isn't executed on a developer machine.

**Comment by olivergierke** [comment]
I think that's a problem in IntelliJ. We explicitly have the `addOutputDirectory` set to `false` (see the [plugin's documentation](https://awhitford.github.io/lombok.maven/lombok-maven-plugin/delombok-mojo.html) for details.

I thought about the CI profile as well but that doesn't work as the general build packages up the JavaDoc for installation into the local repository and the entire reasone the delombok plugin is in place is to make code generated by Lombok appear in that JavaDoc.

**Comment by schauder** [comment]
I agree that this really **should** be fixed in IntelliJ. 
I will create a ticket there.

I'd like to have a workaround for the time being anyway.
Since we don't know how long that might take I'd appreciate a workaround in the meantime that doesn't require constant repetitive action.

Since the JavaDoc plugin gets explicitly configured with the source folder anyway. 
Can we use a different path? 
E.g. `generated-sources-excluded`?

**Comment by schauder** [comment]
Created an Intellij issue: https://youtrack.jetbrains.com/issue/IDEA-184689

**Comment by olivergierke** [comment]
I've tweaked the build setup to move both delomboking and JavaDoc generation to the `ci` and `distribution` profiles.
