### ISSUE TITLE
Add shared documentation resources for a consistent reference documentation styling

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-build#566]
With https://github.com/spring-projects/spring-data-commons/pull/281, we've seen new resources (CSS, JavaScript) that are required to provide a user-friendly table of contents for our documentation. We should add these resources to Spring Data Build and make them available for all of our module documentation builds.

**Comment by olivergierke** [comment]
I have a few local changes to make this work already. Polish and push upcoming.

**Comment by mp911de** [comment]
Pull request #545 brings already references to external resources. I think we need to split up #545 into epub/PDF and resource changes. See https://github.com/spring-projects/spring-doc-resources/tree/master/src/main/resources for the actual contents of `spring-doc-resources`.
