### ISSUE TITLE
Javadoc plugin configuration not working on older Maven versions (e.g. 3.0.3)

### ISSUE THREAD

**Issue by Aloren** [spring-projects/spring-data-build#591]
Trying to build spring-data-aerospike project using spring-data-parent 2.0.8.RELEASE on Teamcity leads to the following error:
```
Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.0:jar (attach-javadocs) 
on project spring-data-aerospike: 
Unable to parse configuration of mojo org.apache.maven.plugins:maven-javadoc-plugin:3.0.0:jar for parameter additionalJOptions: 
Cannot assign configuration entry 'additionalJOptions' with value '-Xdoclint:none' of type java.lang.String to property of type java.lang.String[] -> [Help 1]
```

Current configuration of `maven-javadoc-plugin` looks like that:
```
<additionalJOptions>-Xdoclint:none</additionalJOptions>
```
According to [documentation](https://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html) it should be:
```
    <additionalJOptions>
        <additionalJOption>-Xdoclint:none</additionalJOption>
    </additionalJOptions>
```
Or it can also be specified using:
```
<doclint>none</doclint>
```

**Comment by olivergierke** [comment]
Thanks for reporting this. What puzzles me a bit is that the change that introduced the referenced line is from four months ago and we have successfully published releases since then. What Maven version are you running on your CI server? Maybe we have been using a more recent one that leniently expands the single configuration element into the collection needed by the plugin?

**Comment by Aloren** [comment]
I was not working on spring-data-aerospike all this time so I have no clue how it was built :). I needed to update dependencies right now, so that triggered build on our internal Teamcity.
I've checked maven version on agent:
```
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T07:58:13Z)
Maven home: /opt/maven
Java version: 1.8.0_161, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_IE, platform encoding: UTF-8
OS name: "linux", version: "4.2.0-27-generic", arch: "amd64", family: "unix"
```
This one is not the oldest one...

As a workaround I overridden plugin's configuration in spring-data-aerospike:
```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <configuration combine.self="override">
                    <additionalJOptions>
                        <additionalJOption>-Xdoclint:none</additionalJOption>
                    </additionalJOptions>
                </configuration>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
And it helped.

Any ideas? :)

**Comment by olivergierke** [comment]
We could reproduce the problem on even older versions of Maven (3.0.3). We have been running releases of the Spring Data release train that produced Javadoc. That didn't include the Aerospike module of course.

We're definitely going to fix this, I just wanted to understand what exactly is causing the issue.

P.S.: I wasn't aware of the existence of `combine.self` on `<configuration />`. Learned something new. Thanks for that! 🙃

**Comment by mp911de** [comment]
This issue is reproducible with earlier Maven versions. Ran a couple of tests, here's the result so far:

| Maven Version  | Success/Fail  |
| -------------  | ------------- |
| 3.0.3          |            ❌ |
| 3.2.1          |            ❌ |
| 3.3.1          |            ❌ |
| 3.3.9          |            ✅ |
| 3.5.0          |            ✅ |
| 3.5.2          |            ✅ |

**Comment by olivergierke** [comment]
This is now in place in `master`, `2.0.x` and `1.9.x`. I'll open a separate ticket to add an Enforcer Plugin configuration to require a quite recent Maven version.
