### ISSUE TITLE
Handle JDK 8u181 breaking change to maven-surefire-plugin

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-data-build#662]
The official Docker version of `openjdk:8-jdk` was updated with a patch (see https://github.com/docker-library/openjdk/commit/7a33416016b60c045cf0ba99e82617ed6c130595#diff-fef076ee1e5f270f2c5a93d075150919), causing `maven-surefire-plugin` to break.

This was a backport of a security patch from JDK 8u191, that was incomplete. It introduces a new property, but doesn't provide a default.

Existing Docker-based builds break. Adding the following to any `maven-surefire-plugin` configuration solves the problem:

```
<useSystemClassLoader>false</useSystemClassLoader>
```

Normally such patching would be done on each project, but `spring-data-build` preconfigures `maven-surefire-plugin` for most of the projects, so it needs to be mended here.

**Comment by odrotbohm** [comment]
That's merged to master. In case you think this should be back-ported, please open tickets with the summary copied, cherry-pick the commits but change the summary line of the commit to point to the new tickets.

**Comment by gregturn** [comment]
Thanks @odrotbohm.
