### ISSUE TITLE
Spring data Elasticsearch 4.0.0.DATAES-512-SNAPSHOT dependency failing

### ISSUE THREAD

**Issue by pavanpatel20** [spring-projects/spring-data-build#802]
I am using 4.0.0.DATAES-512-SNAPSHOT in my project, as spring data elasticsearch 4.0 is still not released. I need this as I want to use it on aws and it requires rest client support. 

<dependency>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-elasticsearch</artifactId>
			<version>4.0.0.DATAES-512-SNAPSHOT</version>
		</dependency>

And this dependency recently started giving error when I do mvn clean compile package.

Error:-

Failed to read artifact descriptor for org.springframework.data:spring-data-elasticsearch:jar:4.0.0.DATAES-512-SNAPSHOT: Could not find artifact org.springframework:spring-framework-bom:pom:5.2.0.M1 in repository.spring.snapshot (http://repo.spring.io/snapshot)

I believe below is the culprit in parent pom xml (https://github.com/spring-projects/spring-data-build/blob/master/parent/pom.xml) :-

<spring>5.2.0.M1</spring>

Can someone please look into this issue.

**Comment by odrotbohm** [comment]
Please check your dependency setup. The parent POM is using `libs-snapshot` which contains all release, milestone and snapshot libraries. The error message suggests that something in your build has declared `snapshot` (note the missing `lib-…`). The latter does *not* contain milestone releases.

**Comment by pavanpatel20** [comment]
There has been nothing changed in my setup. I have this dependency from quite sometime and it was working fine. For testing I created a test project and had just below dependency and from repository I removed the springframework directory. So everything is fetched from scratch.

It was just today when I tried to do clean build, it started seeing this error. The parent pom has spring version as 5.2.0.M1 and this version doesn't exists. Some 4 days ago there was a check in to file https://github.com/spring-projects/spring-data-build/commit/115c330b9c4e77b1c69e79d36db9869f03560673 where if you see M has been replaced with SNAPSHOT, I am not sure if that has to be done for spring version 5.2.0.M1 too.

**Comment by odrotbohm** [comment]
I am afraid, I cannot help unless you can share a failing project. All our POMs declare `…/libs-snapshot`. Spring Framework BOM 5.2 M1 [is available](http://repo.spring.io/libs-snapshot/org/springframework/spring-framework-bom/5.2.0.M1/) in those repositories. As indicated already, the thing that's odd is that the error message shows `…/snapshot` being used. I guess you'd have to investigate where this one is coming from.

The commits you see are automated ones from our release procedure and have been used in exactly the same way for years.

**Comment by christophstrobl** [comment]
@pavanpatel20 please add the milestone repository as @odrotbohm suggested and use `spring-data-elasticsearch-3.2.0.M3` instead of snapshots from an already deleted branch.

**Comment by pavanpatel20** [comment]
Attaching my test project, its very simple I am just using 4.0.0.DATAES-512-SNAPSHOT as dependency and trying to build the project.

I have to use 4.0.0.DATAES-512-SNAPSHOT in my project as spring data elasticsearch 4.0 is still not released. Please review pom.xml, its very simple and if you try to do mvn package, thats when I get "Failed to read artifact descriptor for org.springframework.data:spring-data-elasticsearch:jar:4.0.0.DATAES-512-SNAPSHOT: Could not find artifact org.springframework:spring-framework-bom:pom:5.2.0.M1 in repository.spring.snapshot"

[test.zip](https://github.com/spring-projects/spring-data-build/files/3079819/test.zip)

**Comment by odrotbohm** [comment]
As indicated before, you're using `…/snapshot` as repository URL, which is wrong. You *need* to use `…/libs-snapshot`. If I change the URI to use that, `mvn dependency:list -Dsort` works fine. 

Please also note, that as indicated by @christophstrobl, the code that lived in that feature branch has already been merged into master and released with 3.2 M1. So you should be fine using just that.

Even more general: please make sure you always use https URIs to point to repositories to avoid MITM attacks.

**Comment by pavanpatel20** [comment]
Thank you guys for quick response, appreciate your help. God bless you people for supporting the community...:)

Please invalidate this bug

**Comment by odrotbohm** [comment]
Glad you got it working. Happy coding!
