### ISSUE TITLE
Moore bom manages non-existent spring-data-mongodb-cross-store module

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-data-build#804]
It was removed in [this commit](https://github.com/spring-projects/spring-data-mongodb/commit/38d8529b8192a692e75298913132aecb67035ae3#diff-600376dffeb79835ede4a0b285078036) but it looks like the bom wasn't updated.

**Comment by mp911de** [comment]
That's fixed now. Thanks a lot.
